using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Media;

namespace inventory_management.PL.Product
{
    public partial class Form_Category : DevExpress.XtraEditors.XtraForm
    {
        BL.Category.Category category = new BL.Category.Category();

        public Form_Category()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                string TaxValue = Convert.ToInt32(btnTax.EditValue) == 1 ? "Taxé" : "Non Taxé";
                category.add_category(txtName.Text, TaxValue);
                sqlDataSource1.FillAsync();
                txtName.Clear();
                txtName.Select();
                SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                simpleSound.Play();
            } else
            {
                SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                simpleSound.Play();
            }
        }

        private void btnTax_Toggled(object sender, EventArgs e)
        {
            SoundPlayer simpleSound = new SoundPlayer(@"c:\toggle.wav");
            simpleSound.Play();
        }
    }
}