using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Media;

namespace inventory_management.PL.Product
{
    public partial class Form_Tax : DevExpress.XtraEditors.XtraForm
    {
        BL.Tax.Tax tax = new BL.Tax.Tax();

        public Form_Tax()
        {
            InitializeComponent();
            txtName.Select();
            sqlDataSource1.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                tax.add_Tax(txtName.Text, Convert.ToDecimal(txtTax.EditValue));
                sqlDataSource1.FillAsync();
                txtName.Clear();
                txtTax.Clear();
                txtName.Select();
                SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                simpleSound.Play();
            }
            else
            {
                SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                simpleSound.Play();
            }
        }

        private void Form_Tax_KeyDown(object sender, KeyEventArgs e)
        {

            if (e.KeyValue == (char)Keys.Enter)
            {
                this.simpleButton1_Click(sender, e);
            }
        }

        private void txtName_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyValue == (char)Keys.Enter)
            {
                txtTax.Select();
            }
        }

        private void txtTax_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyValue == (char)Keys.Enter)
            {
                this.simpleButton1_Click(sender, e);
                txtTax.Clear();
                txtName.Select();
            }
        }

        private void txtTax_Enter(object sender, EventArgs e)
        {
            txtTax.SelectAll();
        }

        private void txtTax_Click(object sender, EventArgs e)
        {
            txtTax.SelectAll();
        }
    }
}