using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Media;

namespace inventory_management.PL.Product
{
    public partial class Form_Warehouse : DevExpress.XtraEditors.XtraForm
    {
        BL.Warehouse.Warehouse warehouse = new BL.Warehouse.Warehouse();

        public Form_Warehouse()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource2.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource3.FillAsync();
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {

            if (dxValidationProvider1.Validate())
            {
                warehouse.add_Warehouse(txtName.Text, txtAdr.Text, Convert.ToInt32(textEdit1.EditValue), Convert.ToInt32(textEdit11.EditValue));
                sqlDataSource3.FillAsync();
                //txtCode.Clear();
                //txtUnite.Clear();
                //txtCode.Select();
                SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                simpleSound.Play();
            }
            else
            {
                SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                simpleSound.Play();
            }
        }

        private void txtTax_EditValueChanged(object sender, EventArgs e)
        {

        }
    }
}