using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Media;

namespace inventory_management.PL.Product
{
    public partial class Form_Brand : DevExpress.XtraEditors.XtraForm
    {
        BL.Brand.Brand brand = new BL.Brand.Brand();

        public Form_Brand()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        private void textEdit1_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void simpleButton1_Click_1(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                brand.add_Brand(txtName.Text);
                sqlDataSource1.FillAsync();
                SoundPlayer simpleSound = new SoundPlayer(@"c:\sound.wav");
                simpleSound.Play();
            }
        }

        private void Form_Brand_Load(object sender, EventArgs e)
        {

        }
    }
}