using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace inventory_management.PL.Purchase
{
    public partial class Form_Purchase : DevExpress.XtraEditors.XtraForm
    {
        BL.Order.Order order = new BL.Order.Order();

        public Form_Purchase()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource2.FillAsync();

            this.calculeTotalPrice();
        }

        public void calculeTotalPrice()
        {
            txtTotal.Text = order.get_orders_total().ToString();

            if (Convert.ToInt32(txtTax.Text) == 0)
                txtFinal.Text = (Convert.ToDouble(txtTotal.Text) + Convert.ToDouble(txtRemise.Text)).ToString();
            else
                txtFinal.Text = ((Convert.ToDouble(txtTax.Text) * Convert.ToDouble(txtTotal.Text)) + Convert.ToDouble(txtRemise.Text)).ToString();
        }

        private void txtRemise_EditValueChanged(object sender, EventArgs e)
        {
            this.calculeTotalPrice();
        }

        private void txtTax_EditValueChanged(object sender, EventArgs e)
        {
            this.calculeTotalPrice();
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {

        }
    }
}