using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Media;

namespace inventory_management
{
    public partial class Form_Product : DevExpress.XtraEditors.XtraForm
    {
        BL.Product.Product product = new BL.Product.Product();

        public Form_Product()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource2.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource3.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource4.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource5.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource7.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource8.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource9.FillAsync();
        }

        private void Form_Product_Load(object sender, EventArgs e)
        {

        }

            //string Pro_Name,
            //string Ref,
            //int Box,
            //float Box_Price,
            //int Qty_Alert,
            //DateTime Production_Date,
            //DateTime Expiration_Date,
            //DateTime Waiting_period,
            //int Tax_ID,
            //int Ut_ID,
            //int Cate_ID,
            //int Fm_ID,
            //int Brand_ID
            
        private void btnAddNew_Click(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                int product_id = product.add_Product(txtNomProd.Text,txtRefProd.Text, Convert.ToInt32(cbxCoulissant.EditValue), Convert.ToDecimal(cbxPrixCoulissant.EditValue), Convert.ToInt32(txtQteInit.EditValue), Convert.ToInt32(txtQteAlert.EditValue), DateTime.Now, DateTime.Now, DateTime.Now, Convert.ToInt32(txtTax.EditValue), Convert.ToInt32(txtUnit.EditValue), Convert.ToInt32(txtCateg.EditValue), Convert.ToInt32(txtFamille.EditValue), Convert.ToInt32(txtBrand.EditValue));
                product.add_Product_Barcode(txtCodeBar.Text, product_id);
                product.add_Product_Price(Convert.ToInt32(txtQteInit.EditValue), Convert.ToDecimal(txtPrixAchat.EditValue), Convert.ToDecimal(txtPrixDetail.EditValue), Convert.ToDecimal(txtPrixGros.EditValue), Convert.ToDecimal(txtPrixSuperGos.EditValue), product_id);
                product.add_Product_to_warehouse(Convert.ToInt32(txtQteInit.EditValue), Convert.ToInt32(cbxWareHouse.EditValue), product_id); 
                 SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                simpleSound.Play();
            }
            else
            {
                SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                simpleSound.Play();
            }
        }

        private void btnAddFamille_Click(object sender, EventArgs e)
        {
            PL.Product.Form_Family family = new PL.Product.Form_Family();
            family.ShowDialog();
        }

        private void btnAddUnit_Click_1(object sender, EventArgs e)
        {
            PL.Product.Form_Unit unit = new PL.Product.Form_Unit();
            unit.ShowDialog();
        }

        private void btnAddCateg_Click(object sender, EventArgs e)
        {
            PL.Product.Form_Category cate = new PL.Product.Form_Category();
            cate.ShowDialog();
        }

        private void btnAddBrand_Click(object sender, EventArgs e)
        {
            PL.Product.Form_Brand brand = new PL.Product.Form_Brand();
            brand.ShowDialog();
        }

        private void btnADDtax_Click(object sender, EventArgs e)
        {
            PL.Product.Form_Tax tax = new PL.Product.Form_Tax();
            tax.ShowDialog();
        }

        private void simpleButton3_Click(object sender, EventArgs e)
        {
            PL.Product.Form_Warehouse warehouse = new PL.Product.Form_Warehouse();
            warehouse.ShowDialog();
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            Form_Suppliers suppliers = new Form_Suppliers();
            suppliers.ShowDialog();
        }
    }
}