using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Media;

namespace inventory_management
{
    public partial class Form_Product : DevExpress.XtraEditors.XtraForm
    {
        BL.Product.Product product = new BL.Product.Product();

        public Form_Product()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource2.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource3.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource4.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource5.FillAsync();
        }

        private void Form_Product_Load(object sender, EventArgs e)
        {

        }

            //string Pro_Name,
            //string Ref,
            //int Box,
            //float Box_Price,
            //int Qty_Alert,
            //DateTime Production_Date,
            //DateTime Expiration_Date,
            //DateTime Waiting_period,
            //int Tax_ID,
            //int Ut_ID,
            //int Cate_ID,
            //int Fm_ID,
            //int Brand_ID
            
        private void btnAddNew_Click(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate())
            {
                MessageBox.Show(txtRefProd.Text);
                product.add_Product(txtNomProd.Text,txtRefProd.Text, Convert.ToInt32(cbxCoulissant.EditValue), Convert.ToDecimal(cbxPrixCoulissant.EditValue), Convert.ToInt32(txtQteAlert.EditValue), DateTime.Now, DateTime.Now, DateTime.Now, Convert.ToInt32(txtTax.EditValue), Convert.ToInt32(txtUnit.EditValue), Convert.ToInt32(txtCateg.EditValue), Convert.ToInt32(txtFamille.EditValue), Convert.ToInt32(txtBrand.EditValue));
                //sqlDataSource1.FillAsync();
                //txtName.Clear();
                //txtName.Select();
                SoundPlayer simpleSound = new SoundPlayer(@"c:\Added.wav");
                simpleSound.Play();
            }
            else
            {
                SoundPlayer simpleSound = new SoundPlayer(@"c:\ValidationError.wav");
                simpleSound.Play();
            }
        }
    }
}